language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
env:
  global:
    - DISABLE_PYTHON3_WARN="--disable=consider-using-set-comprehension,useless-object-inheritance"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install pip --upgrade
  - pip install -e .[dev,test]
  - pip install pytest --upgrade
  - pip install coveralls
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then DISABLE_PYTHON3_WARN=; fi
  - pylint guessit $DISABLE_PYTHON3_WARN
  - coverage run --source=guessit setup.py test
  - python setup.py build
after_success:
  - coveralls
